### PR TITLE
Fix code generation for `flags`.

### LINKED ISSUE #119: Failure to build component containing flags shape
I am using cargo-component from commit 29fea4af8a28857e6a1fee3df3cd930a3fadad10.

While trying to build a component that contains a `flags` shape (example [here](https://github.com/bytecodealliance/cargo-component/blob/dab8fe09e1f43f7b47aaaa40b275078864f37a7d/example/wit/example.wit)), the following error is presented (reproduced [here](https://github.com/bytecodealliance/cargo-component/actions/runs/5908361401/job/16027700973?pr=118)):
> error[E0433]: failed to resolve: use of undeclared crate or module `wit_bindgen`
 --> src/lib.rs:1:1
  |
1 | cargo_component_bindings::generate!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `wit_bindgen`
  |
  = note: this error originates in the macro `cargo_component_bindings::generate` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0412]: cannot find type `Permissions` in this scope
 --> src/lib.rs:1:1
  |
1 | cargo_component_bindings::generate!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
  |
  = help: consider importing this struct:
          std::fs::Permissions
  = note: this error originates in the macro `cargo_component_bindings::generate` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0433]: failed to resolve: use of undeclared type `Permissions`
 --> src/lib.rs:1:1
  |
1 | cargo_component_bindings::generate!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type `Permissions`
  |
  = help: consider importing this struct:
          std::fs::Permissions
  = note: this error originates in the macro `cargo_component_bindings::generate` (in Nightly builds, run with -Z macro-backtrace for more info)

### PR DESCRIPTION
**Pull request by peterhuene**
This PR updates dependencies and `wit-bindgen` to a commit that has a fix for specifying the path to the `bitflags` crate re-export, allowing `cargo-component` targets to contain `flags` types.

Updated an existing test to cover the use of the `flags` type.

Fixes #119.

### CODE REVIEW

File: crates/macro/src/lib.rs [hunk 1]
```diff
@@ -308,6 +308,7 @@ impl Config {
             exports,
             ownership: self.ownership,
             runtime_path: Some("cargo_component_bindings::rt".to_string()),
+            bitflags_path: Some("cargo_component_bindings::bitflags".to_string()),
```
Comment (sunfishcode) [inline crates/macro/src/lib.rs:311]: This is pre-existing, but should these names be fully qualified with `::` at the start, eg. `::cargo_component_bindings::rt`?

**Review by sunfishcode — APPROVED** [review]

File: crates/macro/src/lib.rs (hunk 1 above)
Comment (peterhuene) [reply crates/macro/src/lib.rs:311]: Definitely couldn't hurt, I'll fix.
